language: node_js
node_js:
- node
script:
  - 'npm run build && git commit -am "build" && git push'
deploy:
  provider: s3
  local_dir: dist
  bucket: mole-client
  access_key_id: AKIAJHKIXN3VCBQQLBWQ
  acl: public_read
  region: us-west-2
  on:
    repo: theonlyjohnny/ssh-mole
    all_branches: true
  cache:
    bundler: true
    directories:
    - node_modules
  secret_access_key:
    secure: x4IRYIZ4Rrc1T7L2p/hLO8BDKQU/GmmDAWVW9GPEAceNNruzROkWicgYJNxE6MMwc1kZUZvd/hYrJ3HV5JDz8l5fvmRWw0Ct2O1oGh5c+k6P/KrlcnNL2iwgG10rGEc3NeeV64+WdUUBq1kdu+7L72mzXZY4+lU/hB6GhbBIe1qm7oJ9JGqnO6yDw7hzqE9hgyjgzpoQEe93pI8qz9Wef0vYr4Oy46NvX7n6EuP3a9lEVTUWsMpwoqaTRpEhbQL6byTssUZYZh7hwF/WGkk6CKkOcKNk3sBt3s7puYY4b0eZd6rDlc+iMtFhhqXeavYP/+edEHFE0QVi30HiR+cIaSZNB1sKAAWJoYQryeEU+deOuZEjloQSLrzIO66IORoVdTgqZ+pD0kFG3Hz/sIAXRBLg6SO1zgdSbMBHaeL40wNkbuCcUteuoCYqOWN9FePEpKeI1JhnzPxmvewd+O4bKdWQXYq4Cs4riT67s6JwaQad80CYE93CaRTYvjHMzyNsCuyC94VodBazMcjMgSCfMNqv3IBU3lX2RvMaWLWU36J3yHNjro9kr4GtGkj7/Z+9/eDaXYs2zAmwE8OHGlRIsSNXM4Du/iFh0ZyV+OS5YEROqMa+7ggAXxEpr/nJzwLRVahnqdDbg/KAGOOSgAbKYBfGzyaRMOmHAFwD2UB3ZXE=
